<h1> Data Science Project: Planning Stage (Individual) </h>

In [24]:
library(tidyverse)
library(repr)
options(repr.matrix.max.rows = 6)
source("cleanup.R")

Warning message in file(filename, "r", encoding = encoding):
“cannot open file 'cleanup.R': No such file or directory”

ERROR: Error in file(filename, "r", encoding = encoding): cannot open the connection

<h2> Data Description </h2>

In [25]:
player_data = read_csv('data/players.csv')
sessions_data = read_csv('data/sessions.csv')
player_data
sessions_data

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    experience subscribe
1   Pro         TRUE
2   Veteran     TRUE
3   Veteran    FALSE
⋮   ⋮          ⋮
194 Amateur    FALSE
195 Amateur    FALSE
196 Pro         TRUE
    hashedEmail
1   f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
2   f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9
3   b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28
⋮   ⋮
194 d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db299bd4fedb06a46ad5bb
195 f19e136ddde68f365afc860c725ccff54307dedd13968e896a9f890c40aea436
196 d9473710057f7d42f36570f0be83817a4eea614029ff90cf50d8889cdd729d11
    played_hours name      gender            Age
1   30.3         Morgan    Male               9
2    3.8         Christian Male              17
3    0.0         Blake     Male              17
⋮   ⋮            ⋮         ⋮                 ⋮
194 0.0          Dylan     Prefer not to say 57
195 2.3          Harlow    Male              17
196 0.2          Ahmed     Other             NA

     hashedEmail
1    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2    36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3    f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
⋮    ⋮
1533 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1534 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1535 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
     start_time       end_time         original_start_time original_end_time
1    30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2    17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3    25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
⋮    ⋮                ⋮                ⋮                   ⋮
1533 28/07/2024 15:36 28/07/2024 15:57 1.72218e+12         1.72218e+12
1534 25/07/2024 06:15 25/07/2024 06:22 1.72189e+12         1.72189e+12
1535 20/05/2024 02:26 20/05/2024 02:45 1.71617e+12         1.71617e+12

<h2> Number of Observations </h2>

In [27]:
observations_for_player_data = nrow(player_data)
observations_for_sessions_data = nrow(sessions_data)

observations_for_player_data
observations_for_sessions_data

[1] 196

[1] 1535

<h2> Number of Variables </h2>

In [28]:
variables_for_player_data = ncol(player_data)
vairables_for_sessions_data = ncol(sessions_data)
variables_for_player_data
vairables_for_sessions_data

[1] 7

[1] 5

<h2> Summary Statistics </h2>

In [29]:
tidy_time = sessions_data |>
    separate(col = start_time,
             into = c('start_date', 'start_time'),
             sep = ' ') |>
    separate(col = end_time,
             into = c('end_date', 'end_time'),
             sep = ' ') 
    

time_difference = sessions_data |>
    mutate(original_time_difference = original_end_time - original_start_time)
  
max_min_avrg_time_difference = time_difference |>
    summarize(max_time = max(original_time_difference, na.rm = TRUE),
             average_time = mean(original_time_difference, na.rm = TRUE),
             min_time = min(original_time_difference, na.rm = TRUE)) 

tidy_time
max_min_avrg_time_difference

     hashedEmail
1    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2    36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3    f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
⋮    ⋮
1533 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1534 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1535 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
     start_date start_time end_date   end_time original_start_time
1    30/06/2024 18:12      30/06/2024 18:24    1.71977e+12
2    17/06/2024 23:33      17/06/2024 23:46    1.71867e+12
3    25/07/2024 17:34      25/07/2024 17:57    1.72193e+12
⋮    ⋮          ⋮          ⋮          ⋮        ⋮
1533 28/07/2024 15:36      28/07/2024 15:57    1.72218e+12
1534 25/07/2024 06:15      25/07/2024 06:22    1.72189e+12
1535 20/05/2024 02:26      20/05/2024 02:45    1.71617e+12
     original_end_time
1    1.71977e+12
2    1.71867e+12
3    1.72193e+12
⋮    ⋮
1533 1.72218e+12
1534 1.72189e+12
1535 1.71617e+12

  max_time average_time min_time
1 2e+07    2909328      0

<h2> Player Data </h2>

In [33]:
player_data

max_min_avrg_hours = player_data |>
    summarize(max_hours = max(played_hours, na.rm = TRUE),
             average_hours = mean(played_hours, na.rm = TRUE),
             min_hours = min(played_hours, na.rm = TRUE)) |>
    round(digits = 2)

max_min_avrg_age = player_data |>
    summarize(max_age = max(Age, na.rm = TRUE),
             average_age = mean(Age, na.rm = TRUE),
             min_age = min(Age, na.rm = TRUE)) |>
    round(digits = 2)

experiences_max_min_avrg_hours = player_data |>
    group_by(experience) |>
    summarize(max_hours = max(Age, na.rm = TRUE),
             average_hours = mean(Age, na.rm = TRUE),
             min_hours = min(Age, na.rm = TRUE)) 

max_min_avrg_hours
max_min_avrg_age
experiences_max_min_avrg_hours

    experience subscribe
1   Pro         TRUE
2   Veteran     TRUE
3   Veteran    FALSE
⋮   ⋮          ⋮
194 Amateur    FALSE
195 Amateur    FALSE
196 Pro         TRUE
    hashedEmail
1   f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
2   f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9
3   b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28
⋮   ⋮
194 d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db299bd4fedb06a46ad5bb
195 f19e136ddde68f365afc860c725ccff54307dedd13968e896a9f890c40aea436
196 d9473710057f7d42f36570f0be83817a4eea614029ff90cf50d8889cdd729d11
    played_hours name      gender            Age
1   30.3         Morgan    Male               9
2    3.8         Christian Male              17
3    0.0         Blake     Male              17
⋮   ⋮            ⋮         ⋮                 ⋮
194 0.0          Dylan     Prefer not to say 57
195 2.3          Harlow    Male              17
196 0.2          Ahmed     Other             NA

  max_hours average_hours min_hours
1 223.1     5.85          0

  max_age average_age min_age
1 58      21.14       9

  experience max_hours average_hours min_hours
1 Amateur    57        21.36508      11
2 Beginner   42        21.65714      17
3 Pro        25        16.92308       9
4 Regular    58        22.02857      10
5 Veteran    46        20.95833      16